# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: speech_response.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='speech_response.proto',
  package='speech_back',
  syntax='proto3',
  serialized_options=_b('\n\025com.proto.speech_backP\001'),
  serialized_pb=_b('\n\x15speech_response.proto\x12\x0bspeech_back\"\"\n\rSpeechRequest\x12\x11\n\ttimeStamp\x18\x01 \x01(\x03\"\x1d\n\x0eSpeechResponse\x12\x0b\n\x03num\x18\x01 \x01(\x03\x32\xb2\x01\n\x11SpeechBackService\x12Q\n\x10SendSpeechStream\x12\x1a.speech_back.SpeechRequest\x1a\x1b.speech_back.SpeechResponse\"\x00(\x01\x30\x01\x12J\n\rSendSpeechOne\x12\x1a.speech_back.SpeechRequest\x1a\x1b.speech_back.SpeechResponse\"\x00\x42\x19\n\x15\x63om.proto.speech_backP\x01\x62\x06proto3')
)




_SPEECHREQUEST = _descriptor.Descriptor(
  name='SpeechRequest',
  full_name='speech_back.SpeechRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='timeStamp', full_name='speech_back.SpeechRequest.timeStamp', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=38,
  serialized_end=72,
)


_SPEECHRESPONSE = _descriptor.Descriptor(
  name='SpeechResponse',
  full_name='speech_back.SpeechResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='num', full_name='speech_back.SpeechResponse.num', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=74,
  serialized_end=103,
)

DESCRIPTOR.message_types_by_name['SpeechRequest'] = _SPEECHREQUEST
DESCRIPTOR.message_types_by_name['SpeechResponse'] = _SPEECHRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SpeechRequest = _reflection.GeneratedProtocolMessageType('SpeechRequest', (_message.Message,), {
  'DESCRIPTOR' : _SPEECHREQUEST,
  '__module__' : 'speech_response_pb2'
  # @@protoc_insertion_point(class_scope:speech_back.SpeechRequest)
  })
_sym_db.RegisterMessage(SpeechRequest)

SpeechResponse = _reflection.GeneratedProtocolMessageType('SpeechResponse', (_message.Message,), {
  'DESCRIPTOR' : _SPEECHRESPONSE,
  '__module__' : 'speech_response_pb2'
  # @@protoc_insertion_point(class_scope:speech_back.SpeechResponse)
  })
_sym_db.RegisterMessage(SpeechResponse)


DESCRIPTOR._options = None

_SPEECHBACKSERVICE = _descriptor.ServiceDescriptor(
  name='SpeechBackService',
  full_name='speech_back.SpeechBackService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=106,
  serialized_end=284,
  methods=[
  _descriptor.MethodDescriptor(
    name='SendSpeechStream',
    full_name='speech_back.SpeechBackService.SendSpeechStream',
    index=0,
    containing_service=None,
    input_type=_SPEECHREQUEST,
    output_type=_SPEECHRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='SendSpeechOne',
    full_name='speech_back.SpeechBackService.SendSpeechOne',
    index=1,
    containing_service=None,
    input_type=_SPEECHREQUEST,
    output_type=_SPEECHRESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_SPEECHBACKSERVICE)

DESCRIPTOR.services_by_name['SpeechBackService'] = _SPEECHBACKSERVICE

# @@protoc_insertion_point(module_scope)
